### ISSUE TITLE
could not find dbmigrator

### ISSUE THREAD

**Issue by salihozkara** [enisn/AbpDevTools#14]
![image](https://github.com/user-attachments/assets/dc39152d-41f8-479a-9ae8-8e8cb6454e8a)

**Comment by enisn** [comment]
Yeah, it checks the project name for better performance:
https://github.com/enisn/AbpDevTools/blob/ef93bd4a282b073a1938c4d89a211632c1543027/src/AbpDevTools/Commands/RunCommand.cs#L128

It should be enhanced.
